//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:json_annotation/json_annotation.dart' as _i1;
import 'package:json_annotation/json_annotation.dart';

/// Indicates type of action that is available
/// for an ally of an opponent during champ select phase.
enum ActionType {
  ///
  @_i1.JsonValue("Pick")
  Pick,

  ///
  @_i1.JsonValue("Ban")
  Ban
}
