//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'league_client.g.dart';

/// Represents a «League of Legends» client
/// that is controlled by a client controller.
@JsonSerializable()
class LeagueClient implements BaseJsonSerializable<LeagueClient> {
  LeagueClient([this.gameflowPhase, this.readyCheckStarted, this.pick]);

  @override
  factory LeagueClient.fromJson(Map<String, dynamic> json) => _$LeagueClientFromJson(json);

  /// Gameflow phase of the client.
  @JsonKey(name: "gameflowPhase")
  GameflowPhase? gameflowPhase;

  /// Time when ready check was initiated.
  @JsonKey(name: "readyCheckStarted", fromJson: unixTimestampToDateTimeNullable, toJson: dateTimeToUnixTimestampNullable)
  DateTime? readyCheckStarted;

  /// Describes champ select phase.
  @JsonKey(name: "pick")
  PickStage? pick;

  @override
  Map<String, dynamic> toJson() => _$LeagueClientToJson(this);
}
