//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'pick_stage.g.dart';

/// Represents select phase in league client
/// with the data about teams, summoners, champions, bans etc.
@JsonSerializable()
class PickStage implements BaseJsonSerializable<PickStage> {
  PickStage(this.userPosition, this.bansPlanned, this.allies, this.enemies, [this.actionRequestedAt]);

  @override
  factory PickStage.fromJson(Map<String, dynamic> json) => _$PickStageFromJson(json);

  /// Index of the allies array that corresponds to the user.
  @JsonKey(name: "userPosition")
  int userPosition;

  ///
  @JsonKey(name: "bansPlanned")
  bool bansPlanned;

  /// Time when the last action was requested from summoner(s).
  @JsonKey(name: "actionRequestedAt", fromJson: unixTimestampToDateTimeNullable, toJson: dateTimeToUnixTimestampNullable)
  DateTime? actionRequestedAt;

  /// Members of the user's team.
  /// Index in the array points to player position in the pick order.
  @JsonKey(name: "allies")
  List<Summoner> allies;

  /// Members of an opposing team.
  /// Index in the array points to player position in the pick order.
  @JsonKey(name: "enemies")
  List<Summoner> enemies;

  @override
  Map<String, dynamic> toJson() => _$PickStageToJson(this);
}
