//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:json_annotation/json_annotation.dart' as _i1;
import 'package:json_annotation/json_annotation.dart';

/// Queue type of pick stage.
/// Determines the rules of the game and rules for the pick stage.
enum QueueType {
  ///
  @_i1.JsonValue("Custom")
  Custom,

  ///
  @_i1.JsonValue("DraftPick")
  DraftPick,

  ///
  @_i1.JsonValue("RankedSolo")
  RankedSolo,

  ///
  @_i1.JsonValue("BlindPick")
  BlindPick,

  ///
  @_i1.JsonValue("RankedFlex")
  RankedFlex
}
