//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:json_annotation/json_annotation.dart' as _i1;
import 'package:json_annotation/json_annotation.dart';

/// Indicates player role in the «League of Legends».
enum Role {
  ///
  @_i1.JsonValue("Top")
  Top,

  ///
  @_i1.JsonValue("Jungle")
  Jungle,

  ///
  @_i1.JsonValue("Middle")
  Middle,

  ///
  @_i1.JsonValue("Bottom")
  Bottom,

  ///
  @_i1.JsonValue("Support")
  Support,

  ///
  @_i1.JsonValue("Any")
  Any
}
