name: lcc_api_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: 'none'
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0-80.1.beta <3.0.0'


dependencies:
  json_annotation: ^4.3.0
  dart_jsonwebtoken: ^2.4.0
  http: ^0.13.4
#   path: ^1.8.0

dev_dependencies:
  json_serializable: ^6.1.3
  build_runner: ^2.1.7
  lints: ^1.0.0
  test: ^1.16.0
