//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:json_annotation/json_annotation.dart' as _i1;
import 'package:json_annotation/json_annotation.dart';

/// Type of the client event.
enum ClientEventType {
  /// Client game glow phase was changed.
  @_i1.JsonValue("GameflowPhaseChanged")
  GameflowPhaseChanged
}
