//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:json_annotation/json_annotation.dart' as _i1;
import 'package:json_annotation/json_annotation.dart';

/// Type of the device event
enum DeviceEventType {
  /// Device was added
  @_i1.JsonValue("DeviceAdded")
  DeviceAdded,

  /// Some of device properties were changed
  @_i1.JsonValue("DeviceChanged")
  DeviceChanged,

  /// Device was removed
  @_i1.JsonValue("DeviceRemoved")
  DeviceRemoved
}
