//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:json_annotation/json_annotation.dart' as _i1;
import 'package:json_annotation/json_annotation.dart';

/// Type of the event.
/// Specify how event message should be deserialized.
enum EventType {
  /// Event message should be deserialized as [DeviceEvent]
  @_i1.JsonValue("Device")
  Device,

  /// Event message should be deserialized as [ClientEvent]
  @_i1.JsonValue("Client")
  Client,

  /// Event message should be deserialized as [PickEvent]
  @_i1.JsonValue("Pick")
  Pick,

  /// Event message should be deserialized as [CommandEvent]
  @_i1.JsonValue("Command")
  Command
}
