//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'action_requested_parameters.g.dart';

///
@JsonSerializable()
class ActionRequestedParameters implements BaseJsonSerializable<ActionRequestedParameters> {
  ActionRequestedParameters(this.requestedAt, this.isAllyAction, this.firstActorPosition, this.actorsCount, this.type);

  @override
  factory ActionRequestedParameters.fromJson(Map<String, dynamic> json) => _$ActionRequestedParametersFromJson(json);

  /// When this action was requested by league client.
  @JsonKey(name: "requestedAt", fromJson: unixTimestampToDateTime, toJson: dateTimeToUnixTimestamp)
  DateTime requestedAt;

  /// Is action is prescribed for an ally or an opponent.
  @JsonKey(name: "isAllyAction")
  bool isAllyAction;

  /// Index of the allies or opponents array
  /// that specifies first summoner of the action. [0..4]
  @JsonKey(name: "firstActorPosition")
  int firstActorPosition;

  /// How many summoners participates in the action. [1..5]
  @JsonKey(name: "actorsCount")
  int actorsCount;

  /// Type of the action.
  @JsonKey(name: "type")
  ActionType type;

  @override
  Map<String, dynamic> toJson() => _$ActionRequestedParametersToJson(this);
}
