//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'action_completed_parameters.g.dart';

///
@JsonSerializable()
class ActionCompletedParameters implements BaseJsonSerializable<ActionCompletedParameters> {
  ActionCompletedParameters(this.actorPosition, this.isActorAnAlly, [this.championId]);

  @override
  factory ActionCompletedParameters.fromJson(Map<String, dynamic> json) => _$ActionCompletedParametersFromJson(json);

  /// Position of the actor in ally or enemy team ([0..4]).
  @JsonKey(name: "actorPosition")
  int actorPosition;

  /// Whether actor is on ally or enemy team.
  @JsonKey(name: "isActorAnAlly")
  bool isActorAnAlly;

  /// ID of a picked or banned champion.
  @JsonKey(name: "championId")
  int? championId;

  @override
  Map<String, dynamic> toJson() => _$ActionCompletedParametersToJson(this);
}
