//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'action_requested_parameters.g.dart';

///
@JsonSerializable()
class ActionRequestedParameters implements BaseJsonSerializable<ActionRequestedParameters> {
  ActionRequestedParameters(this.requestedAt, this.isAllyAction, this.actorsRange, this.type);

  @override
  factory ActionRequestedParameters.fromJson(Map<String, dynamic> json) => _$ActionRequestedParametersFromJson(json);

  /// When this action was requested by league client.
  @JsonKey(name: "requestedAt", fromJson: unixTimestampToDateTime, toJson: dateTimeToUnixTimestamp)
  DateTime requestedAt;

  /// Is action is prescribed for an ally or an opponent.
  @JsonKey(name: "isAllyAction")
  bool isAllyAction;

  /// Specifies range of actors the action was requested from ([0..4]).
  @JsonKey(name: "actorsRange")
  ValueRange actorsRange;

  /// Type of the action.
  @JsonKey(name: "type")
  ActionType type;

  @override
  Map<String, dynamic> toJson() => _$ActionRequestedParametersToJson(this);
}
