//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'champ_select_parameters.g.dart';

/// Parameters of the /client/reportChampSelectStarted method.
@JsonSerializable()
class ChampSelectParameters implements BaseJsonSerializable<ChampSelectParameters> {
  ChampSelectParameters(this.userPosition, this.enemiesCount, this.alliesRoles);

  @override
  factory ChampSelectParameters.fromJson(Map<String, dynamic> json) => _$ChampSelectParametersFromJson(json);

  /// Index of the user in allies array.
  @JsonKey(name: "userPosition")
  int userPosition;

  /// Count of matched enemies.
  @JsonKey(name: "enemiesCount")
  int enemiesCount;

  /// Array of matched allies' roles
  @JsonKey(name: "alliesRoles")
  List<Role> alliesRoles;

  @override
  Map<String, dynamic> toJson() => _$ChampSelectParametersToJson(this);
}
