//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'skin_changed_parameters.g.dart';

///
@JsonSerializable()
class SkinChangedParameters implements BaseJsonSerializable<SkinChangedParameters> {
  SkinChangedParameters(this.summonerPosition, this.skinId);

  @override
  factory SkinChangedParameters.fromJson(Map<String, dynamic> json) => _$SkinChangedParametersFromJson(json);

  /// Position of player whose skin has been changed in allies array. [0..4]
  @JsonKey(name: "summonerPosition")
  int summonerPosition;

  /// New skin id.
  @JsonKey(name: "skinId")
  int skinId;

  @override
  Map<String, dynamic> toJson() => _$SkinChangedParametersToJson(this);
}
