//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:lcc_api_dart/model.dart';
import 'package:lcc_api_dart/src/utils/base_json_serializable.dart';

part 'command_response.g.dart';

///
@JsonSerializable()
class CommandResponse extends ApiResponse {
  CommandResponse() : super();

  @override
  factory CommandResponse.fromJson(Map<String, dynamic> json) => _$CommandResponseFromJson(json);

  ///
  @JsonKey(name: "commandId")
  late int commandId;

  @override
  Map<String, dynamic> toJson() => _$CommandResponseToJson(this);
}
