//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'jwt_payload.g.dart';

/// Payload of the access token
@JsonSerializable()
class JwtPayload implements BaseJsonSerializable<JwtPayload> {
  JwtPayload(this.userId, this.username, this.deviceId, this.deviceType, this.iat, this.exp);

  @override
  factory JwtPayload.fromJson(Map<String, dynamic> json) => _$JwtPayloadFromJson(json);

  /// Id of the authorized user
  @JsonKey(name: "userId")
  int userId;

  /// Name of the authorized user
  @JsonKey(name: "username")
  String username;

  /// Id of the device that is authorized under the user
  @JsonKey(name: "deviceId")
  int deviceId;

  /// Type of the device that is authorized under the user
  @JsonKey(name: "deviceType")
  DeviceType deviceType;

  /// Time when the token was issued
  @JsonKey(name: "iat")
  int iat;

  /// Time when the token will be expired
  @JsonKey(name: "exp")
  int exp;

  @override
  Map<String, dynamic> toJson() => _$JwtPayloadToJson(this);
}
