//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:json_annotation/json_annotation.dart' as _i1;
import 'package:json_annotation/json_annotation.dart';

/// Determines who can execute specific method
enum MethodAccessPolicy {
  /// Method can be accessed with token given to the client controller
  @_i1.JsonValue("Controller")
  Controller,

  /// Method can be accessed with token given to the remote device
  @_i1.JsonValue("Device")
  Device,

  /// Method can be accessed with any access token
  @_i1.JsonValue("Both")
  Both
}
