//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:json_annotation/json_annotation.dart' as _i1;
import 'package:json_annotation/json_annotation.dart';

///
enum MethodError {
  ///
  @_i1.JsonValue("InternalServerError")
  InternalServerError,

  ///
  @_i1.JsonValue("WrongApiKeyError")
  WrongApiKey,

  ///
  @_i1.JsonValue("WrongAccessTokenError")
  WrongAccessToken,

  ///
  @_i1.JsonValue("AccessTokenNotProvidedError")
  AccessTokenNotProvided,

  ///
  @_i1.JsonValue("WrongNicknameEmailOrPasswordError")
  WrongNicknameEmailOrPassword,

  ///
  @_i1.JsonValue("JsonParsingError")
  JsonParsing,

  ///
  @_i1.JsonValue("MissingMethodParametersError")
  MissingMethodParameters,

  ///
  @_i1.JsonValue("InvalidCommandParametersError")
  InvalidCommandParameters,

  ///
  @_i1.JsonValue("InvalidMethodParameterError")
  InvalidMethodParameter,

  ///
  @_i1.JsonValue("InvalidOperationError")
  InvalidOperation,

  ///
  @_i1.JsonValue("ListenerIsAlreadyRegisteredError")
  ListenerIsAlreadyRegistered
}
