//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'value_range.g.dart';

/// Specifies value range borders.
/// Used for taking values from an array.
/// Values count is {@see entitiesCount} and they are taken from {@see firstIndex},
/// so the range is from {@see firstIndex} to {@see firstIndex} + {@see entitiesCount}.
@JsonSerializable()
class ValueRange implements BaseJsonSerializable<ValueRange> {
  ValueRange(this.firstIndex, this.entitiesCount);

  @override
  factory ValueRange.fromJson(Map<String, dynamic> json) => _$ValueRangeFromJson(json);

  /// Index of the first element of the array that needs to be taking.
  @JsonKey(name: "firstIndex")
  int firstIndex;

  /// How many elements needs to be taken.
  @JsonKey(name: "entitiesCount")
  int entitiesCount;

  @override
  Map<String, dynamic> toJson() => _$ValueRangeToJson(this);
}
