//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'dart:async';

import 'package:lcc_api_dart/categories.dart';
import 'package:lcc_api_dart/core.dart';
import 'package:lcc_api_dart/exceptions.dart';
import 'package:lcc_api_dart/model.dart';

class ClientCategory implements IClientCategory {
  ClientCategory(this._api);

  final ILccApi _api;

  @override
  Future setGameflowPhase(GameflowPhase? gameflowPhase, int? readyCheckStarted) async {
    final SetGameflowPhaseParameters parameters = SetGameflowPhaseParameters(gameflowPhase, readyCheckStarted);
    /* <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved. */
    /* 	TODO: Add parameters validation */
    /* </auto-generated-safe-area> */
    await _api.executeWithParameters(r'client/setGameflowPhase', parameters, withAccessToken: true);
  }

  @override
  Future<int> sendCommand(int controllerId, CommandName commandName, SomeParametrizedCommandArgs? commandArgs) async {
    final SendCommandParameters parameters = SendCommandParameters(controllerId, commandName, commandArgs);
    /* <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved. */
    /* 	TODO: Add parameters validation */
    /* </auto-generated-safe-area> */
    final CommandResponse response = await _api.executeWithParametersAndResponse(
        r'client/sendCommand', parameters, (Map<String, dynamic> json) => CommandResponse.fromJson(json),
        withAccessToken: true);
    /* <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved. */
    /* 	TODO: Add response validation */
    /* </auto-generated-safe-area> */
    return response.commandId;
  }

  @override
  Future setCommandResult(int commandId, CommandResult result) async {
    final SetCommandResultParameters parameters = SetCommandResultParameters(commandId, result);
    /* <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved. */
    /* 	TODO: Add parameters validation */
    /* </auto-generated-safe-area> */
    await _api.executeWithParameters(r'client/setCommandResult', parameters, withAccessToken: true);
  }
}
