//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'dart:async';

import 'package:larc_api_dart/categories.dart';
import 'package:larc_api_dart/core.dart';
import 'package:larc_api_dart/exceptions.dart';
import 'package:larc_api_dart/model.dart';

class IdentityCategory implements IIdentityCategory {
  IdentityCategory(this._api);

  final ILarcApi _api;

  @override
  Future<int> register(String username, String email, String password) async {
    final RegisterParameters parameters = RegisterParameters(username, email, password);
    /* <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved. */
    /* 	TODO: Add parameters validation */
    /* </auto-generated-safe-area> */
    final RegistrationResponse response = await _api.executeWithParametersAndResponse(
        r'identity/register', parameters, (Map<String, dynamic> json) => RegistrationResponse.fromJson(json));
    /* <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved. */
    /* 	TODO: Add response validation */
    /* </auto-generated-safe-area> */
    return response.registeredId;
  }

  @override
  Future<String> confirm(int accountId, String code, String deviceName, DeviceType deviceType) async {
    final ConfirmationParameters parameters = ConfirmationParameters(accountId, code, deviceName, deviceType);
    /* <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved. */
    /* 	TODO: Add parameters validation */
    /* </auto-generated-safe-area> */
    final AccessTokenResponse response = await _api.executeWithParametersAndResponse(
        r'identity/confirm', parameters, (Map<String, dynamic> json) => AccessTokenResponse.fromJson(json));
    /* <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved. */
    /* 	TODO: Add response validation */
    /* </auto-generated-safe-area> */
    return response.accessToken;
  }

  @override
  Future resendConfirmation(int accountId) async {
    final ResendConfirmationParameters parameters = ResendConfirmationParameters(accountId);
    /* <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved. */
    /* 	TODO: Add parameters validation */
    /* </auto-generated-safe-area> */
    await _api.executeWithParameters(r'identity/resendConfirmation', parameters);
  }

  @override
  Future<String> login(String login, String password, String deviceName, DeviceType deviceType) async {
    final LoginParameters parameters = new LoginParameters(login, password, deviceName, deviceType);
    /* <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved. */
    /* 	TODO: Add parameters validation */
    /* </auto-generated-safe-area> */
    final AccessTokenResponse response = await _api.executeWithParametersAndResponse<AccessTokenResponse, LoginParameters>(
        "identity/login", parameters, (json) => AccessTokenResponse.fromJson(json),
        withAccessToken: false);
    /* <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved. */
    /* 	TODO: Add response validation */
    /* </auto-generated-safe-area> */
    return response.accessToken;
  }

  @override
  Future<ProfileInfo> getProfileInfo() async {
    final ProfileInfoResponse response = await _api.executeWithResponse(
        r'identity/getProfileInfo', (Map<String, dynamic> json) => ProfileInfoResponse.fromJson(json),
        withAccessToken: true);
    /* <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved. */
    /* 	TODO: Add response validation */
    /* </auto-generated-safe-area> */
    return response.profile;
  }

  @override
  Future<String> refreshAccessToken() async {
    final AccessTokenResponse response = await _api.executeWithResponse(
        r'identity/refreshAccessToken', (Map<String, dynamic> json) => AccessTokenResponse.fromJson(json),
        withAccessToken: true);
    /* <auto-generated-safe-area> Code within tag borders shouldn't cause incorrect behavior and will be preserved. */
    /* 	TODO: Add response validation */
    /* </auto-generated-safe-area> */
    return response.accessToken;
  }
}
