//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:lcc_api_dart/model.dart';
import 'package:lcc_api_dart/src/utils/base_json_serializable.dart';

part 'profile_info.g.dart';

///
@JsonSerializable()
class ProfileInfo implements BaseJsonSerializable<ProfileInfo> {
  ProfileInfo([this.summonerId]);

  @override
  factory ProfileInfo.fromJson(Map<String, dynamic> json) => _$ProfileInfoFromJson(json);

  ///
  @JsonKey(name: "summonerId")
  String? summonerId;

  @override
  Map<String, dynamic> toJson() => _$ProfileInfoToJson(this);
}
