//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'confirmation_parameters.g.dart';

/// Parameters of the /identity/confirm method.
@JsonSerializable()
class ConfirmationParameters implements BaseJsonSerializable<ConfirmationParameters> {
  ConfirmationParameters(this.accountId, this.code, this.deviceName, this.deviceType);

  @override
  factory ConfirmationParameters.fromJson(Map<String, dynamic> json) => _$ConfirmationParametersFromJson(json);

  /// ID of an account that should be confirmed.
  @JsonKey(name: "accountId")
  int accountId;

  /// 6-digits code to confirm account.
  @JsonKey(name: "code")
  String code;

  /// Name of the device that will be authorized under the user.
  @JsonKey(name: "deviceName")
  String deviceName;

  /// Type of the device that will be authorized under the user.
  @JsonKey(name: "deviceType")
  DeviceType deviceType;

  @override
  Map<String, dynamic> toJson() => _$ConfirmationParametersToJson(this);
}
