//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'register_parameters.g.dart';

/// Parameters of the /identity/register method.
@JsonSerializable()
class RegisterParameters implements BaseJsonSerializable<RegisterParameters> {
  RegisterParameters(this.username, this.email, this.password);

  @override
  factory RegisterParameters.fromJson(Map<String, dynamic> json) => _$RegisterParametersFromJson(json);

  /// Name of the user that will be registered.
  @JsonKey(name: "username")
  String username;

  /// Email of the user that will be registered.
  @JsonKey(name: "email")
  String email;

  /// User's password
  @JsonKey(name: "password")
  String password;

  @override
  Map<String, dynamic> toJson() => _$RegisterParametersToJson(this);
}
