//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'resend_confirmation_parameters.g.dart';

/// Parameters of the /identity/resendConfirmation method.
@JsonSerializable()
class ResendConfirmationParameters implements BaseJsonSerializable<ResendConfirmationParameters> {
  ResendConfirmationParameters(this.accountId);

  @override
  factory ResendConfirmationParameters.fromJson(Map<String, dynamic> json) => _$ResendConfirmationParametersFromJson(json);

  /// ID of an account that should be confirmed..
  @JsonKey(name: "accountId")
  int accountId;

  @override
  Map<String, dynamic> toJson() => _$ResendConfirmationParametersToJson(this);
}
