//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'champion_command_args.g.dart';

/// Describes args for a command that requires a champion ID.
@JsonSerializable()
class ChampionCommandArgs implements BaseJsonSerializable<ChampionCommandArgs> {
  ChampionCommandArgs(this.championId);

  @override
  factory ChampionCommandArgs.fromJson(Map<String, dynamic> json) => _$ChampionCommandArgsFromJson(json);

  /// ID of a champion that should be hovered upon, picked or banned.
  @JsonKey(name: "championId")
  int championId;

  @override
  Map<String, dynamic> toJson() => _$ChampionCommandArgsToJson(this);
}
