//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:json_annotation/json_annotation.dart' as _i1;
import 'package:json_annotation/json_annotation.dart';

/// Indicates command that is sent to client controller to be executed by it.
enum CommandName {
  /// Client controller should decline league match.
  @_i1.JsonValue("DeclineMatch")
  DeclineMatch,

  /// Client controller should accept league match.
  @_i1.JsonValue("AcceptMatch")
  AcceptMatch,

  /// Test
  @_i1.JsonValue("SomeParametrized")
  SomeParametrized
}
