//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'command.g.dart';

/// Describes command for client controller to execute.
@JsonSerializable()
class Command implements BaseJsonSerializable<Command> {
  Command(this.id, this.name, [this.args]);

  @override
  factory Command.fromJson(Map<String, dynamic> json) => _$CommandFromJson(json);

  /// Identifier of the command.
  @JsonKey(name: "id")
  int id;

  /// Name of the command.
  @JsonKey(name: "name")
  CommandName name;

  /// Arguments of the command.
  @JsonKey(name: "args")
  ChampionCommandArgs? args;

  @override
  Map<String, dynamic> toJson() => _$CommandToJson(this);
}
