//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:lcc_api_dart/model.dart';
import 'package:lcc_api_dart/src/utils/base_json_serializable.dart';

part 'some_parametrized_command_args.g.dart';

///
@JsonSerializable()
class SomeParametrizedCommandArgs implements BaseJsonSerializable<SomeParametrizedCommandArgs> {
  SomeParametrizedCommandArgs(this.commandParam);

  @override
  factory SomeParametrizedCommandArgs.fromJson(Map<String, dynamic> json) => _$SomeParametrizedCommandArgsFromJson(json);

  ///
  @JsonKey(name: "commandParam")
  String commandParam;

  @override
  Map<String, dynamic> toJson() => _$SomeParametrizedCommandArgsToJson(this);
}
