//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'client_controller.g.dart';

/// Representation of the device that is owned by the user
/// if it's computer that controls league of legends client
@JsonSerializable()
class ClientController implements BaseJsonSerializable<ClientController> {
  ClientController(this.id, this.name, this.isOnline, [this.client]);

  @override
  factory ClientController.fromJson(Map<String, dynamic> json) => _$ClientControllerFromJson(json);

  /// Identifier of the controller.
  @JsonKey(name: "id")
  int id;

  /// Name of the controller.
  @JsonKey(name: "name")
  String name;

  /// Whether the device is online
  @JsonKey(name: "isOnline")
  bool isOnline;

  ///
  @JsonKey(name: "client")
  LeagueClient? client;

  @override
  Map<String, dynamic> toJson() => _$ClientControllerToJson(this);
}
