//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'device.g.dart';

/// Representation of the device that is owned by the user
/// if it's a mobile device or whatever remote
@JsonSerializable()
class Device implements BaseJsonSerializable<Device> {
  Device(this.id, this.type, this.name, this.isOnline);

  @override
  factory Device.fromJson(Map<String, dynamic> json) => _$DeviceFromJson(json);

  /// Identifier of the device
  @JsonKey(name: "id")
  int id;

  /// Type of the device
  @JsonKey(name: "type")
  DeviceType type;

  /// Name of the device
  @JsonKey(name: "name")
  String name;

  /// Whether the device is online
  @JsonKey(name: "isOnline")
  bool isOnline;

  @override
  Map<String, dynamic> toJson() => _$DeviceToJson(this);
}
