//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:json_annotation/json_annotation.dart' as _i1;
import 'package:json_annotation/json_annotation.dart';

/// Indicates type of the device that user owns.
enum DeviceType {
  ///
  @_i1.JsonValue("Controller")
  Controller,

  ///
  @_i1.JsonValue("Phone")
  Phone
}
