//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'access_token_response.g.dart';

///
@JsonSerializable()
class AccessTokenResponse extends ApiResponse {
  AccessTokenResponse() : super();

  @override
  factory AccessTokenResponse.fromJson(Map<String, dynamic> json) => _$AccessTokenResponseFromJson(json);

  ///
  @JsonKey(name: "accessToken")
  late String accessToken;

  @override
  Map<String, dynamic> toJson() => _$AccessTokenResponseToJson(this);
}
