//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'profile_info_response.g.dart';

///
@JsonSerializable()
class ProfileInfoResponse extends ApiResponse {
  ProfileInfoResponse() : super();

  @override
  factory ProfileInfoResponse.fromJson(Map<String, dynamic> json) => _$ProfileInfoResponseFromJson(json);

  ///
  @JsonKey(name: "profile")
  late ProfileInfo profile;

  @override
  Map<String, dynamic> toJson() => _$ProfileInfoResponseToJson(this);
}
