//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

import 'package:dart_library_generator/utilities.dart';
import 'package:decimal/decimal.dart';
import 'package:json_annotation/json_annotation.dart';
import 'package:larc_api_dart/model.dart';
import 'package:larc_api_dart/src/utils/base_json_serializable.dart';

part 'registration_response.g.dart';

/// Response of the /identity/register method.
@JsonSerializable()
class RegistrationResponse extends ApiResponse {
  RegistrationResponse() : super();

  @override
  factory RegistrationResponse.fromJson(Map<String, dynamic> json) => _$RegistrationResponseFromJson(json);

  /// ID of the user that has been registered.
  /// Used to confirm account.
  @JsonKey(name: "registeredId")
  late int registeredId;

  @override
  Map<String, dynamic> toJson() => _$RegistrationResponseToJson(this);
}
